TG-684,686: Api Documentation for druidreport,clientlog and experimen…
project-sunbird/sunbird.org-docs pull request #620
Opened 2020-12-02 10:00 UTC by RevathiKotla

…t api

2020-12-02 10:03 UTC, keshavprasadms commented
Hello @RevathiKotla,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://620.qa.docs.sunbird.org/api-documentation/ .<br/> **Note:** Only _api-documentation_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://620.qa.docs.sunbird.org/api-documentation/apis/clientlogapi// <br /> - http://620.qa.docs.sunbird.org/api-documentation/apis/clientlogapi// <br /> - http://620.qa.docs.sunbird.org/api-documentation/apis/druidreportapi// <br /> - http://620.qa.docs.sunbird.org/api-documentation/apis/druidreportapi// <br /> - http://620.qa.docs.sunbird.org/api-documentation/apis/experimentapi// <br /> - http://620.qa.docs.sunbird.org/api-documentation/apis/experimentapi// <br />  <br/> **Modified sections are -** <br />

2020-12-02 16:14 UTC, keshavprasadms commented
Hello @RevathiKotla,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://620.qa.docs.sunbird.org/api-documentation/ .<br/> **Note:** Only _api-documentation_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://620.qa.docs.sunbird.org/api-documentation/apis/clientlogapi// <br /> - http://620.qa.docs.sunbird.org/api-documentation/apis/clientlogapi// <br /> - http://620.qa.docs.sunbird.org/api-documentation/apis/druidreportapi// <br /> - http://620.qa.docs.sunbird.org/api-documentation/apis/druidreportapi// <br /> - http://620.qa.docs.sunbird.org/api-documentation/apis/experimentapi// <br /> - http://620.qa.docs.sunbird.org/api-documentation/apis/experimentapi// <br />  <br/> **Modified sections are -** <br />

2020-12-03 06:56 UTC, anandp504 requested changes
Please resolve the required changes

2020-12-03 06:56 UTC, anandp504 commented on apis/clientlogapi/clientlogapi.yaml
> +                os: mac
Why are the values for most of the device spec empty?

2020-12-03 06:56 UTC, anandp504 commented on apis/clientlogapi/clientlogapi.yaml
> +            description: exception of the log event
Can we use the stacktrace of the error log instead of exception?

2020-12-03 06:56 UTC, anandp504 commented on apis/clientlogapi/clientlogapi.yaml
> +        example:
Please have some valid values for each of the device spec fields.

2020-12-03 06:56 UTC, anandp504 commented on apis/clientlogapi/clientlogapi.yaml
> +      ClientLogAPI-200OK:
What is ClientLogAPI-200OK? Please name the title appropriately instead of using Http error codes.

2020-12-03 06:56 UTC, anandp504 commented on apis/experimentapi/experimentapi.yaml
> +    description: "- The Experiment API is used to create an experiment with user or device specifications. The Operations include create, get experiment  \n- The URL for Experiment API(S) is\
The Experiment API is used to run experiments on the efficacy of new features for a set of targeted users using user and device specifications. The API supports operations to create experiments and retrieve an already existing experiments. \n- The URL for Experiment API(S) is\
      \ `/data/v1/experiment

2020-12-03 06:56 UTC, anandp504 commented on apis/experimentapi/experimentapi.yaml
> +          This API is used for create a new experiment based on particular user or device filters.  Respective user can create a experiment based on users filters(any user specific details like organ
This API is used for create a new experiment based on particular user filters such as organisation, board, medium etc. or device filters such as device id, device location state/district, first access dates etc.

2020-12-03 06:56 UTC, anandp504 commented on apis/experimentapi/experimentapi.yaml
> +            description: Success example for experiment create
An example for successful experiment creation

2020-12-03 06:56 UTC, anandp504 commented on apis/experimentapi/experimentapi.yaml
> +                    summary: IF_NEW_EXPERIMENT
Do we need to have IF in the summary?

2020-12-03 06:56 UTC, anandp504 commented on apis/experimentapi/experimentapi.yaml
> +                    summary: If_Experiment_Already_Exists
Do we need to have IF in the summary?

2020-12-03 06:56 UTC, anandp504 commented on apis/experimentapi/experimentapi.yaml
> +            description: Bad Request for create experiment
Bad Request for Create Experiment API

2020-12-03 06:56 UTC, anandp504 commented on apis/experimentapi/experimentapi.yaml
> +                    description: Response example when request is missing
Does it mean the RequestBody is missing?

2020-12-03 06:56 UTC, anandp504 commented on apis/experimentapi/experimentapi.yaml
> +                          request.expId: Created By should not be empty
The field request.expId but the description says Created By should not be empty.

2020-12-03 06:56 UTC, anandp504 commented on apis/experimentapi/experimentapi.yaml
> +                  MissingDateFields:
What is the difference between RequiredFields and MissingFields scenario?

2020-12-03 06:56 UTC, anandp504 commented on apis/experimentapi/experimentapi.yaml
> +                    summary: Missing_Date_Fields
Please use a descriptive message for the summary.

2020-12-03 06:56 UTC, anandp504 commented on apis/experimentapi/experimentapi.yaml
> +                          data.startDate: Experiment Start_Date should not be empty
Do we need underscores for the fields such as Start_Date. Also, do the field names be first letter capitalized?

2020-12-03 06:56 UTC, anandp504 commented on apis/experimentapi/experimentapi.yaml
> +            description: Internal Server Error example for experiment create
Internal Server Error example for create experiment API

2020-12-03 06:56 UTC, anandp504 commented on apis/experimentapi/experimentapi.yaml
> +          This API is used for get particular experiment based on experiment id
The get experiment API is used for retrieving the details about an existing experiment using the experiment id.

2020-12-03 06:56 UTC, anandp504 commented on apis/experimentapi/experimentapi.yaml
> +            description: Success example for get particular experiment
An example for a successful retrieval of an existing experiment using the Get Experiment API.

2020-12-03 06:56 UTC, anandp504 commented on apis/experimentapi/experimentapi.yaml
> +                        description: Experiment to redirect all users with device_state as Karnataka and first_access in range of october month to different app page
description: Experiment to redirect all users with device_state as Karnataka and first_access in the range of the month of October 2019 to a different app landing page.

2020-12-03 06:56 UTC, anandp504 commented on apis/experimentapi/experimentapi.yaml
> +                    summary: If_Experiment_Doesnt_Exists
Do we need the If in the summary?

2020-12-03 06:56 UTC, anandp504 commented on apis/experimentapi/experimentapi.yaml
> +           description: name of the experiment
Capitalize the first letter of the description and keep it consistent across all description entries.

2020-12-03 06:56 UTC, anandp504 commented on apis/experimentapi/experimentapi.yaml
> +           description: Experiment type - either user or device
Type of the Experiment. Currently supported types are User and Device. Do we also support one in every 'n' Users or Device using modulus as part of this API?

2020-12-03 06:56 UTC, anandp504 commented on apis/experimentapi/experimentapi.yaml
> +      CreateExistedExperiment-200OK:
What does CreatedExistedExperiment mean?

2020-12-04 10:23 UTC, keshavprasadms commented
Hello @RevathiKotla,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://620.qa.docs.sunbird.org/api-documentation/ .<br/> **Note:** Only _api-documentation_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://620.qa.docs.sunbird.org/api-documentation/apis/clientlogapi// <br /> - http://620.qa.docs.sunbird.org/api-documentation/apis/clientlogapi// <br /> - http://620.qa.docs.sunbird.org/api-documentation/apis/druidreportapi// <br /> - http://620.qa.docs.sunbird.org/api-documentation/apis/druidreportapi// <br /> - http://620.qa.docs.sunbird.org/api-documentation/apis/experimentapi// <br /> - http://620.qa.docs.sunbird.org/api-documentation/apis/experimentapi// <br />  <br/> **Modified sections are -** <br />

2020-12-04 10:31 UTC, keshavprasadms commented
Hello @RevathiKotla,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://620.qa.docs.sunbird.org/api-documentation/ .<br/> **Note:** Only _api-documentation_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://620.qa.docs.sunbird.org/api-documentation/apis/clientlogapi// <br /> - http://620.qa.docs.sunbird.org/api-documentation/apis/clientlogapi// <br /> - http://620.qa.docs.sunbird.org/api-documentation/apis/druidreportapi// <br /> - http://620.qa.docs.sunbird.org/api-documentation/apis/druidreportapi// <br /> - http://620.qa.docs.sunbird.org/api-documentation/apis/experimentapi// <br /> - http://620.qa.docs.sunbird.org/api-documentation/apis/experimentapi// <br />  <br/> **Modified sections are -** <br />

2020-12-04 12:57 UTC, keshavprasadms commented
Hello @RevathiKotla,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://620.qa.docs.sunbird.org/api-documentation/ .<br/> **Note:** Only _api-documentation_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://620.qa.docs.sunbird.org/api-documentation/apis/clientlogapi// <br /> - http://620.qa.docs.sunbird.org/api-documentation/apis/clientlogapi// <br /> - http://620.qa.docs.sunbird.org/api-documentation/apis/druidreportapi// <br /> - http://620.qa.docs.sunbird.org/api-documentation/apis/druidreportapi// <br /> - http://620.qa.docs.sunbird.org/api-documentation/apis/experimentapi// <br /> - http://620.qa.docs.sunbird.org/api-documentation/apis/experimentapi// <br />  <br/> **Modified sections are -** <br />

2020-12-04 13:04 UTC, keshavprasadms commented
Hello @RevathiKotla,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://620.qa.docs.sunbird.org/api-documentation/ .<br/> **Note:** Only _api-documentation_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://620.qa.docs.sunbird.org/api-documentation/apis/clientlogapi// <br /> - http://620.qa.docs.sunbird.org/api-documentation/apis/clientlogapi// <br /> - http://620.qa.docs.sunbird.org/api-documentation/apis/druidreportapi// <br /> - http://620.qa.docs.sunbird.org/api-documentation/apis/druidreportapi// <br /> - http://620.qa.docs.sunbird.org/api-documentation/apis/experimentapi// <br /> - http://620.qa.docs.sunbird.org/api-documentation/apis/experimentapi// <br />  <br/> **Modified sections are -** <br />

2020-12-04 14:25 UTC, merged