SC-2139 First cut for location open-api-v3 model transformation
project-sunbird/sunbird.org-docs pull request #628
Opened 2020-12-04 08:17 UTC by Hari-stackroute

2020-12-04 08:20 UTC, keshavprasadms commented
Hello @Hari-stackroute,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://628.qa.docs.sunbird.org/api-documentation/ .<br/> **Note:** Only _api-documentation_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://628.qa.docs.sunbird.org/api-documentation/apis/locationapi// <br />  <br/> **Modified sections are -** <br />

2020-12-07 05:39 UTC, Sunitashelar requested changes

2020-12-07 07:34 UTC, keshavprasadms commented
Hello @Hari-stackroute,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://628.qa.docs.sunbird.org/api-documentation/ .<br/> **Note:** Only _api-documentation_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://628.qa.docs.sunbird.org/api-documentation/apis/locationapi// <br />  <br/> **Modified sections are -** <br />

2020-12-07 09:05 UTC, Hari-stackroute commented on apis/locationapi/locationapi.yaml
> +        description: 'To make use of any User-Feed API, you require authorization. Raise a request to the administrator for the use of the API. You will receive the authorization key. Specify the key
Changes done @Sunitashelar

2020-12-07 09:05 UTC, Hari-stackroute commented on apis/locationapi/locationapi.yaml
> +        description: 'To make use of any User-Feed API, you require authorization. Raise a request to the administrator for the use of the API. You will receive the authorization key. Specify the key
Changes done @Sunitashelar

2020-12-07 16:21 UTC, Sunitashelar commented on apis/locationapi/locationapi.yaml
> +        description: 'To make use of any User-Feed API, you require authorization. Raise a request to the administrator for the use of the API. You will receive the authorization key. Specify the key
Done

2020-12-07 16:21 UTC, Sunitashelar approved these changes

2020-12-07 16:21 UTC, merged