SB-21838 Adding opensaber api
project-sunbird/sunbird.org-docs pull request #631
Opened 2020-12-06 19:46 UTC by sknirmalkar89

2020-12-06 19:49 UTC, keshavprasadms commented
Hello @sknirmalkar89,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://631.qa.docs.sunbird.org/api-documentation/ .<br/> **Note:** Only _api-documentation_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://631.qa.docs.sunbird.org/api-documentation/apis/opensaber// <br /> - http://631.qa.docs.sunbird.org/api-documentation/apis/opensaber// <br />  <br/> **Modified sections are -** <br />

2020-12-07 17:09 UTC, Sunitashelar requested changes

2020-12-07 18:27 UTC, sknirmalkar89 commented on apis/opensaber/opensaberapi.yaml
> +        description: To make use of any Group API, you require authorization. Raise a
Updated

2020-12-07 18:28 UTC, sknirmalkar89 commented on apis/opensaber/opensaberapi.yaml
> +        This api is used to read record registry
Done

2020-12-07 18:36 UTC, keshavprasadms commented
Hello @sknirmalkar89,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://631.qa.docs.sunbird.org/api-documentation/ .<br/> **Note:** Only _api-documentation_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://631.qa.docs.sunbird.org/api-documentation/apis/opensaber// <br /> - http://631.qa.docs.sunbird.org/api-documentation/apis/opensaber// <br />  <br/> **Modified sections are -** <br />

2020-12-07 18:40 UTC, keshavprasadms commented
Hello @sknirmalkar89,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://631.qa.docs.sunbird.org/api-documentation/ .<br/> **Note:** Only _api-documentation_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://631.qa.docs.sunbird.org/api-documentation/apis/opensaber// <br /> - http://631.qa.docs.sunbird.org/api-documentation/apis/opensaber// <br />  <br/> **Modified sections are -** <br />

2020-12-08 06:09 UTC, Sunitashelar approved these changes

2020-12-08 06:10 UTC, merged