Isuse #SB-21758 feat: Chatbot API Documentation
project-sunbird/sunbird.org-docs pull request #643
Opened 2020-12-10 10:05 UTC by JagadishPujari

2020-12-10 10:07 UTC, keshavprasadms commented
Hello @JagadishPujari,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://643.qa.docs.sunbird.org/3.5.0/ .<br/> **Note:** Only _3.5.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://643.qa.docs.sunbird.org/3.5.0/apis/chatbotapi// <br /> - http://643.qa.docs.sunbird.org/3.5.0/apis/chatbotapi// <br />  <br/> **Modified sections are -** <br />

2020-12-10 18:19 UTC, Sunitashelar requested changes

2020-12-10 18:19 UTC, Sunitashelar commented on apis/chatbotapi/chatbotapi.yaml
> +  title: Chat bot API(s)
Should be 'Chatbot'

2020-12-11 05:37 UTC, keshavprasadms commented
Hello @JagadishPujari,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://643.qa.docs.sunbird.org/3.5.0/ .<br/> **Note:** Only _3.5.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://643.qa.docs.sunbird.org/3.5.0/apis/chatbotapi// <br /> - http://643.qa.docs.sunbird.org/3.5.0/apis/chatbotapi// <br />  <br/> **Modified sections are -** <br />

2020-12-11 05:41 UTC, keshavprasadms commented
Hello @JagadishPujari,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://643.qa.docs.sunbird.org/3.5.0/ .<br/> **Note:** Only _3.5.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://643.qa.docs.sunbird.org/3.5.0/apis/chatbotapi// <br /> - http://643.qa.docs.sunbird.org/3.5.0/apis/chatbotapi// <br />  <br/> **Modified sections are -** <br />

2020-12-11 06:35 UTC, SMYALTAMASH commented on apis/chatbotapi/chatbotapi.yaml
> +  /bot:
this should be /chat/bot @JagadishPujari , please make sure you add /chat to all the paths below as well.

2020-12-11 06:36 UTC, SMYALTAMASH commented on apis/chatbotapi/index.html
> +		<script src="https://rebilly.github.io/ReDoc/releases/v1.19.1/redoc.min.js"> </script>
this is a wrong script URL! check the api-documentation branch contentapis index.html and update accordingly.

2020-12-11 07:02 UTC, keshavprasadms commented
Hello @JagadishPujari,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://643.qa.docs.sunbird.org/api-documentation/ .<br/> **Note:** Only _api-documentation_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://643.qa.docs.sunbird.org/api-documentation/apis/chatbotapi// <br /> - http://643.qa.docs.sunbird.org/api-documentation/apis/chatbotapi// <br />  <br/> **Modified sections are -** <br />

2020-12-13 16:24 UTC, merged