Issue #SB-23271 fix: adding modifications in df apis
project-sunbird/sunbird.org-docs pull request #724
Opened 2021-02-19 13:55 UTC by VenkatKadiveti

2021-02-19 13:57 UTC, keshavprasadms commented
Hello @VenkatKadiveti,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://724.qa.docs.sunbird.org/3.7.0/ .<br/> **Note:** Only _3.7.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://724.qa.docs.sunbird.org/3.7.0/apis/discussionForum// <br /> - http://724.qa.docs.sunbird.org/3.7.0/apis/discussionForum// <br />  <br/> **Modified sections are -** <br />

2021-02-22 04:22 UTC, SMYALTAMASH commented on apis/discussionForum/discussionForum.yaml
> +- url: https://staging.sunbirded.org/discussions/api
IT should be DNS/api/discussion

2021-02-23 07:03 UTC, keshavprasadms commented
Hello @VenkatKadiveti,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://724.qa.docs.sunbird.org/3.7.0/ .<br/> **Note:** Only _3.7.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://724.qa.docs.sunbird.org/3.7.0/apis/discussionForum// <br /> - http://724.qa.docs.sunbird.org/3.7.0/apis/discussionForum// <br />  <br/> **Modified sections are -** <br />

2021-02-23 18:34 UTC, keshavprasadms commented
Hello @VenkatKadiveti,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://724.qa.docs.sunbird.org/3.7.0/ .<br/> **Note:** Only _3.7.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://724.qa.docs.sunbird.org/3.7.0/apis/discussionForum// <br /> - http://724.qa.docs.sunbird.org/3.7.0/apis/discussionForum// <br />  <br/> **Modified sections are -** <br />

2021-02-23 18:41 UTC, Sunitashelar requested changes

2021-02-23 18:41 UTC, Sunitashelar commented on apis/discussionForum/discussionForum.yaml
> +externalDocs:
Are lines  11 - 13 required?

2021-02-23 18:41 UTC, Sunitashelar commented on apis/discussionForum/discussionForum.yaml
> +  /discussion/category/{cid}:
lines 154 - 160 are the same as lines 107 - 113. is this correct?

2021-02-23 18:41 UTC, Sunitashelar commented on apis/discussionForum/discussionForum.yaml
> +        This app allow the user to delete a topic in nodebb
Is this correct? does not match title of API

2021-02-23 18:41 UTC, Sunitashelar commented on apis/discussionForum/discussionForum.yaml
> +        This app allow the user to delete a topic in nodebb
Is this correct? does not match title

2021-02-23 18:41 UTC, Sunitashelar commented on apis/discussionForum/discussionForum.yaml
> +      summary: DisableCategories
This is a repeat of line 387. please check

2021-02-23 18:41 UTC, Sunitashelar commented on apis/discussionForum/discussionForum.yaml
> +        This api is used for creating the user in Nodebb.
This description is the same as on line 679. clarify the difference in the two APIs

2021-02-23 18:41 UTC, Sunitashelar commented on apis/discussionForum/discussionForum.yaml
> +      operationId: DaleteTagsToTopic
This does not match the title. please check.

2021-02-23 18:41 UTC, Sunitashelar commented on apis/discussionForum/discussionForum.yaml
> +          - Backend Route: http://nodebb-service:4567/discussions/api/v2/topics/{tid}/pin
please check the backend route

2021-02-23 18:41 UTC, Sunitashelar commented on apis/discussionForum/discussionForum.yaml
> +      summary: Get group list
is this a repeat of line 1812?

2021-02-23 19:44 UTC, keshavprasadms commented
Hello @VenkatKadiveti,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://724.qa.docs.sunbird.org/3.7.0/ .<br/> **Note:** Only _3.7.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://724.qa.docs.sunbird.org/3.7.0/apis/discussionForum// <br /> - http://724.qa.docs.sunbird.org/3.7.0/apis/discussionForum// <br />  <br/> **Modified sections are -** <br />

2021-02-26 10:37 UTC, Sunitashelar commented
Closing the PR without merging due to conflicts. Spoke to Venkat and new PR will be sent.

2021-02-26 10:37 UTC, closed without merging