Documentation for 3.9.0
project-sunbird/sunbird.org-docs pull request #755
Opened 2021-04-21 09:21 UTC by sreeragksgh

2021-04-21 09:26 UTC, keshavprasadms commented
Hello @sreeragksgh,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://755.qa.docs.sunbird.org/3.9.0/ .<br/> **Note:** Only _3.9.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://755.qa.docs.sunbird.org/3.9.0/apis/userapi// <br />  <br/> **Modified sections are -** <br />

2021-04-21 09:42 UTC, keshavprasadms commented
Hello @sreeragksgh,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://755.qa.docs.sunbird.org/3.9.0/ .<br/> **Note:** Only _3.9.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://755.qa.docs.sunbird.org/3.9.0/apis/userapi// <br />  <br/> **Modified sections are -** <br />

2021-04-21 09:56 UTC, keshavprasadms commented
Hello @sreeragksgh,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://755.qa.docs.sunbird.org/3.9.0/ .<br/> **Note:** Only _3.9.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://755.qa.docs.sunbird.org/3.9.0/apis/userapi// <br />  <br/> **Modified sections are -** <br />

2021-04-21 10:16 UTC, keshavprasadms commented
Hello @sreeragksgh,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://755.qa.docs.sunbird.org/3.9.0/ .<br/> **Note:** Only _3.9.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://755.qa.docs.sunbird.org/3.9.0/apis/userapi// <br />  <br/> **Modified sections are -** <br />

2021-04-22 06:06 UTC, keshavprasadms commented
Hello @sreeragksgh,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://755.qa.docs.sunbird.org/3.9.0/ .<br/> **Note:** Only _3.9.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://755.qa.docs.sunbird.org/3.9.0/apis/userapi// <br />  <br/> **Modified sections are -** <br />

2021-04-22 14:23 UTC, keshavprasadms commented
Hello @sreeragksgh,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://755.qa.docs.sunbird.org/3.9.0/ .<br/> **Note:** Only _3.9.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://755.qa.docs.sunbird.org/3.9.0/apis/userapi// <br />  <br/> **Modified sections are -** <br />

2021-04-22 15:24 UTC, keshavprasadms commented
Hello @sreeragksgh,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://755.qa.docs.sunbird.org/3.9.0/ .<br/> **Note:** Only _3.9.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://755.qa.docs.sunbird.org/3.9.0/apis/userapi// <br />  <br/> **Modified sections are -** <br />

2021-05-03 12:46 UTC, keshavprasadms commented
Hello @sreeragksgh,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://755.qa.docs.sunbird.org/3.9.0/ .<br/> **Note:** Only _3.9.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://755.qa.docs.sunbird.org/3.9.0/apis/userapi// <br />  <br/> **Modified sections are -** <br />

2021-05-03 12:57 UTC, keshavprasadms commented
Hello @sreeragksgh,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://755.qa.docs.sunbird.org/3.9.0/ .<br/> **Note:** Only _3.9.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://755.qa.docs.sunbird.org/3.9.0/apis/userapi// <br />  <br/> **Modified sections are -** <br />

2021-05-03 13:20 UTC, keshavprasadms commented
Hello @sreeragksgh,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://755.qa.docs.sunbird.org/3.9.0/ .<br/> **Note:** Only _3.9.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://755.qa.docs.sunbird.org/3.9.0/apis/userapi// <br />  <br/> **Modified sections are -** <br />

2021-05-04 07:34 UTC, keshavprasadms commented
Hello @sreeragksgh,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://755.qa.docs.sunbird.org/3.9.0/ .<br/> **Note:** Only _3.9.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://755.qa.docs.sunbird.org/3.9.0/apis/userapi// <br />  <br/> **Modified sections are -** <br />

2021-05-04 11:02 UTC, keshavprasadms commented
Hello @sreeragksgh,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://755.qa.docs.sunbird.org/3.9.0/ .<br/> **Note:** Only _3.9.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://755.qa.docs.sunbird.org/3.9.0/apis/userapi// <br />  <br/> **Modified sections are -** <br />

2021-05-05 09:39 UTC, merged

2021-05-05 09:39 UTC, Sunitashelar requested changes

2021-05-05 09:39 UTC, Sunitashelar commented on apis/userapi/userapi.yaml
> +                                name: Karnataka
@sreeragksgh @mohitga request that we do not use actual names, etc. in Sunbird documentation. Can we replace 'Karnataka' 'Belgavi' etc. with variable names providing these as examples? This is a global comment. Further down there are references to other districts, States and towns too.

2021-05-05 09:39 UTC, Sunitashelar commented on apis/userapi/userapi.yaml
> +                          channel: dikshapreprodcustodian
@sreeragksgh @mohitga please remove all references to diksha and any specific servers unless necessary from Sunbird documentation.