SB-22862 - Collection CSV API end documentation
project-sunbird/sunbird.org-docs pull request #759
Opened 2021-05-06 09:09 UTC by Jayaprakash8887

2021-05-06 09:16 UTC, keshavprasadms commented
Hello @Jayaprakash8887,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://759.qa.docs.sunbird.org/3.9.0/ .<br/> **Note:** Only _3.9.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://759.qa.docs.sunbird.org/3.9.0/apis/collectioncsvapi// <br /> - http://759.qa.docs.sunbird.org/3.9.0/apis/collectioncsvapi// <br />  <br/> **Modified sections are -** <br />

2021-05-17 05:53 UTC, keshavprasadms commented
Hello @Jayaprakash8887,<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://759.qa.docs.sunbird.org/3.9.0/ .<br/> **Note:** Only _3.9.0_ version was generated for PR preview. <br/><br/> **Modified pages are -** <br />- http://759.qa.docs.sunbird.org/3.9.0/apis/collectioncsvapi// <br /> - http://759.qa.docs.sunbird.org/3.9.0/apis/collectioncsvapi// <br />  <br/> **Modified sections are -** <br />

2021-05-17 06:15 UTC, Sunitashelar requested changes

2021-05-17 06:15 UTC, Sunitashelar commented on apis/collectioncsvapi/collectioncsvapi.yaml
> +          description: 'Collection id to upload. It should be unique and same as csv file identifier'
@Jayaprakash8887 globally modify 'id' to ID

2021-05-17 06:15 UTC, Sunitashelar commented on apis/collectioncsvapi/collectioncsvapi.yaml
> +          description: 'SUCCESS. The "TOC Upload" operation was successful!'
@Jayaprakash8887 modify the message to ' SUCCESS. The TOC was uploaded successfully.'

2021-05-17 06:15 UTC, Sunitashelar commented on apis/collectioncsvapi/collectioncsvapi.yaml
> +        This API is associated with download collection in csv format.
@Jayaprakash8887 can this description be changed to ' This API is used to download the collection in .csv format.'?

2021-05-17 06:15 UTC, Sunitashelar commented on apis/collectioncsvapi/collectioncsvapi.yaml
> +          description: "The Content Type entity is the media type of the resource. Possible\
@Jayaprakash8887 please refer to the earlier comment on the use of \ to mark line breaks. this is a global comment.

2021-05-17 06:15 UTC, Sunitashelar commented on apis/collectioncsvapi/collectioncsvapi.yaml
> +          description: 'SUCCESS. The "TOC Download" operation was successful!'
@Jayaprakash8887 refer to earlier success message sentence framing.

2021-05-18 09:04 UTC, closed without merging

2021-05-18 09:05 UTC, Jayaprakash8887 commented
Created new pull request against 4.0. #764